# -*- coding: utf-8 -*-
"""Streamlit_proyectofinal_taxis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIdybrbFowd1r_O5rXBkxGTXjn1Fzdno
"""